### ISSUE TITLE
Create a single use token - Error

### ISSUE THREAD

**Issue by Rart3001** [mercadopago/px-android_services#9]
I try to get a card token single use, and always get the same error:

`Error: invalid location - error: bad_request - status - 400`

this is my code:

```
private void testCardTokenRequest(){

        //Get the user public key
        final String publicKey = "TEST-ad365c37-8012-4014-84f5-6c895b3f8e0a";
        Log.i(TAG, "publicKey = " + publicKey);

        // Init MercadoPagoServices object with public key
        MercadoPagoServices mMercadoPagoServices = new MercadoPagoServices.Builder()
                .setContext(this)
                .setPublicKey(publicKey)
                .build();

        Identification identification = new Identification();
        identification.setNumber("12345678");
        identification.setType("CI-V");

        Cardholder cardholder = new Cardholder();
        cardholder.setIdentification(identification);
        cardholder.setName("APRO PEDRO PEREZ");

        CardToken mCardToken = new CardToken();
        mCardToken.setCardholder(cardholder);
        mCardToken.setCardNumber("5177076164300010");
        mCardToken.setDevice(PaymentsListActivity.this);
        mCardToken.setExpirationMonth(12);
        mCardToken.setExpirationYear(2018);
        mCardToken.setSecurityCode("123");


        mMercadoPagoServices.createToken(mCardToken, new Callback<Token>() {
            @Override
            public void success(@NonNull Token token) {
                Log.i(TAG, "Card token = " + token.getId());
            }

            @Override
            public void failure(@NonNull ApiException error) {

                Log.e(TAG, "requestCardToken Error: "+error.getMessage()+" - error: "+error.getError()+" - status - "+error.getStatus());
              
            }
        });

    }
```

**Comment by osielcc** [comment]
i have the same error :/

**Comment by Rart3001** [comment]
I read the documentation and no see nothing about that error, i maked a question in stackoverflow in spanish, and don't get any response, and really the error is not descriptive . [here the question](https://es.stackoverflow.com/questions/132897/mercadopago-error-al-crear-un-token-de-uso-%C3%BAnico-com-mercadopagoservices1)

**Comment by joelibaceta** [comment]
Thanks for report @Rart3001, the issue has been assigned and we will be working to fix it as soon as possible.

**Comment by valeserber** [comment]
@Rart3001 Hi!
Make sure you are sending the context of the current Activity in this line:
`````java
mCardToken.setDevice(context);
`````
Also, you need to set a valid **Identification Type**. You can check the identification types available for your public key [here](https://api.mercadopago.com/v1/identification_types?public_key=TEST-ad365c37-8012-4014-84f5-6c895b3f8e0a)

**Comment by valeserber** [comment]
@Rart3001 You are using this public key which belongs to Argentina
````java
final String publicKey = "TEST-ad365c37-8012-4014-84f5-6c895b3f8e0a";
````
You should register in Mercado Pago Venezuela if you want to use "CI-V", and then use the public key you will find in your [credentials](https://www.mercadopago.com/mla/account/credentials).

**Comment by sergiomeza** [comment]
I'm getting the same error when the device GPS is ON, i don't know why, but seems to work **OK** when the GPS is off, a bug maybe? Thanks

**Comment by valeserber** [comment]
Hi!
- The error _"invalid location"_ is being fixed at the moment. Tomorrow the fix will be deployed.
- `````java  Error: Invalid cardholder.identification.type: CI-V in site_id: MLA `````  this means you are still using a public key from Argentina

**Comment by Rart3001** [comment]
@valeserber, @joelibaceta 

This code worked fine before,  and this not work more after some time.
I maked a new test, i run the same code and turn off the location service (GPS) on my device and i can get the token without problem, i think maybe is a bug in the service side?.

**Comment by Rart3001** [comment]
@valeserber, Yes, I knew what the error `Error: Invalid cardholder.identification.type: CI-V in site_id: MLA ` means:  I just wanted to clarify that it was not my problem ;)

**Comment by sergiomeza** [comment]
Hi, was the _"invalid location"_  error finally fixed? thanks!

**Comment by valeserber** [comment]
@sergiomeza yes! :)
